add link & fix typo
FederatedScopeTeam/FederatedScopeTeam.github.io pull request #8
Opened 2022-04-06 04:12 UTC by Osier-Yi

2022-04-06 05:30 UTC, joneswong commented on _docs/19-privacy-attacks.md
> +Users are welcome to contribute their own attack methods to FederatedScope. Please refer [Contributing to FederatedScope]({{"/docs/contributor/"}}) for more details.
please change to `{{ "/docs/contributor/" | relative_url }}`

2022-04-06 05:31 UTC, joneswong commented on _docs/19-privacy-attacks.md
> +* If the attack actions also happen at the end of the FL training, users need to overload the client class and modify its'callback_funcs_for_finish` function.
the syntax seems inconsistent

2022-04-06 05:32 UTC, joneswong requested changes
Please fix the issues. Thanks!

2022-04-06 06:17 UTC, Osier-Yi commented on _docs/19-privacy-attacks.md
> +Users are welcome to contribute their own attack methods to FederatedScope. Please refer [Contributing to FederatedScope]({{"/docs/contributor/"}}) for more details.
fix~

2022-04-06 06:17 UTC, Osier-Yi commented on _docs/19-privacy-attacks.md
> +* If the attack actions also happen at the end of the FL training, users need to overload the client class and modify its'callback_funcs_for_finish` function.
fix

2022-04-07 03:05 UTC, FederatedScopeTeam commented on _docs/19-privacy-attacks.md
> +Before calling the attack module, the user should make sure that the FL has been set up. For more details of setting up FL, please refer [quick start]({{"/docs/quick-start/" | relative_url }}) and [s
It is necessary to put a space in front of permalink, i.e., `{{ "/doc/quick-start/" | relative_url }}`

2022-04-07 03:06 UTC, FederatedScopeTeam requested changes
See my inline comment. thx!

2022-04-07 07:00 UTC, Osier-Yi commented on _docs/19-privacy-attacks.md
> +Before calling the attack module, the user should make sure that the FL has been set up. For more details of setting up FL, please refer [quick start]({{"/docs/quick-start/" | relative_url }}) and [s
> It is necessary to put a space in front of permalink, i.e., `{{ "/doc/quick-start/" | relative_url }}`

fix~

2022-04-07 08:53 UTC, FederatedScopeTeam approved these changes
Approve!

2022-04-07 08:56 UTC, joneswong approved these changes
LGTM

2022-04-07 08:57 UTC, merged